# Generated by Django 4.2.14 on 2024-07-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashapp', '0003_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='no_of_likes',
        ),
    ]
